version: "3.7"
services:
  prowlarr-indexers:
    container_name: prowlarr-indexers
    image: cr.hotio.dev/hotio/prowlarr:testing
    restart: unless-stopped
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/arr/config/prowlarr:/config