version: "3.7"
services:
  bazarr-subtitles:
    container_name: bazarr-subtitles
    image: cr.hotio.dev/hotio/bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/arr/config/bazarr:/config
      - /mnt/ssd/arr/data/media/movies:/movies #optional
      - /mnt/ssd/arr/data/media/tv:/tv