version: "3.7"
services:
  sonarr-tv:
    container_name: sonarr-tv
    image: cr.hotio.dev/hotio/sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/arr/config/sonarr:/config
      - /mnt/ssd/arr/data:/data