version: "3.7"
services:
  readarr-books:
    container_name: readarr-books
    image: cr.hotio.dev/hotio/readarr:testing
    restart: unless-stopped
    ports:
      - "8787:8787"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/ssd/arr/config/readarr:/config
      - /mnt/ssd/arr/data:/data