version: "3.7"
services:
  requestrr:
    container_name: requestrr-chatbot
    image: darkalfx/requestrr
    restart: unless-stopped
    hostname: requestrr
    ports:
      - "4545:4545"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/pi/config/requestrr:/root/config